wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1668421796.771802
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.8.8
      5: 0.13.5
      8:
      - 5
